version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=andboard
      - POSTGRES_PASSWORD=pass1234
    ports:
      - '5432:5432'
    volumes:
      - andboard:/var/lib/postgresql/data
volumes:
  andboard:
    driver: local
